name: Build & UI Screenshot

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4

      # - name: Set up Java
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: temurin
      #     java-version: 17

      - name: Download Ivy Engine
        run: |
          wget https://download.axonivy.com/13.1.1/AxonIvyDesigner13.1.1.2506271313_Linux_x64.zip -O ivy-engine.zip
          unzip ivy-engine.zip -d ivy-engine

      - name: Build Axon Ivy Project
        run: |
          ./ivy-engine/bin/ivyEngineCli.sh \
            -application com.axonivy.cli.build \
            -data $(pwd)/workspace \
            -projectDir $(pwd)

      - name: Start Ivy Engine
        run: |
          ./ivy-engine/bin/ivyEngine.sh > ivy.log 2>&1 &

          echo "Waiting for Ivy Engine to be ready..."

          for i in {1..60}; do
            if curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 | grep -q "200"; then
              echo "Ivy Engine is ready"
              exit 0
            fi
            sleep 2
          done

          echo "Ivy Engine failed to start"
          echo "===== LOG ====="
          cat ivy.log
          exit 1

      # - name: Install Playwright
      #   run: |
      #     npm install -D playwright
      #     npx playwright install --with-deps

      # - name: Run UI Screenshot Script
      #   run: |
      #     node screenshot.js

      # - name: Upload Screenshots
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: screenshots
      #     path: screenshots/